modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="server_utils_api" # <-- Corrigido para bater com o código Java
version="1.0.4"
displayName="Server Utilities API"
authors="Forge Development Team"
description='''
    A core utility library used for managing cross-platform server packets, network synchronizations, and internal API structures for multi-server performance optimization.
    '''

[[dependencies.server_utils_api]] # <-- Corrigido aqui também
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.server_utils_api]] # <-- E aqui também
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"